import type { NextPage } from 'next'
import Head from 'next/head'
import TableResult from '../components/table-result'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Dashboard Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TableResult />

    </div>
  )
}

export default Home
